---
title: "R Notebook"
output: html_notebook
---

# Régression

``` {r echo=FALSE}
#installer et télécharger le package xlsx
install.packages("xlsx")
install.packages("rJava")
install.packages("xlsxjars")
install.packages("readxl")
install.packages("corrplot")
install.packages("Hmisc")
```

```{r}
# Ouverture du fichier Excel et importation des données présentes sur la feuille 1
library(xlsx)
library(readxl)
library(corrplot)
library(Hmisc)
data <- read_excel("data_final_facteurs_fusionne_2.xlsx", 1)
```

```{r}
# Etude des correlations
dataReduce <- data[, c(4,5,7,9,11,13,15,17,19,21,23,25)]
corMat <- rcorr(as.matrix(dataReduce))
corMat
```

```{r}
# Veification de la p-value
cor.test(x = data$return_rf[!is.na(data$return_rf) & !is.na(data$beta)], y = data$beta[!is.na(data$return_rf) & !is.na(data$beta)])
cor.test(x = data$return_rf[!is.na(data$return_rf) & !is.na(data$AIM)], y = data$AIM[!is.na(data$return_rf) & !is.na(data$AIM)])
cor.test(x = data$return_rf[!is.na(data$return_rf) & !is.na(data$illiq_amihud)], y = data$illiq_amihud[!is.na(data$return_rf) & !is.na(data$illiq_amihud)])
```


```{r}
# corrplot(corMat, type="upper", order="hclust", tl.col="black", tl.srt=45)
# corrplot.mixed(corMat, lower.col = "black")
# corrplot(corMat, p.mat = pMat$p, sig.level = 0.50)
```


```{r}
# Etude des paramètres au cours du temps
x = c()
y = c()
year = 1965
month = 1
date = 0
paramName = "AIM_t1"
while (year < 2005) {
  dataTest =  data[data$month == month & data$year == year,]
  r <- cor(x = dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)], y = dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)], method = "pearson")
  mean(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)])
  mean(dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)])
  x <- c(x,date)
  y <- c(y,mean(dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)]))
  month = month + 1
  date = date + 1
  if (month == 13) {
    month = 1
    year = year + 1
  }
}
plot(x,y, ylab = paramName, xlab = "Temps", type = "l")
```

```{r}
dataTest =  data[data$stock_number <= 20 & data$month == 1 & data,]
dataTest
```
# Gestion active

```{r}
getMax<-function(l, nb) {
  result = c(1:nb)
  for (i in l) {
    
  }
}
```

```{r}
x = c()
y = c()
year = 1965
month = 1
nbAsset = 10
paramName = "AIM_t1"
ptfPast = c()
ptfCurr = c()
dataSing = list()
pnl = 0

dataTest =  data[data$month == month & data$year == year,]
dataTest2 =  data[data$month == month & data$year == year + 1,]
stockNumber = dataTest$stock_number[!is.na(dataTest$return_rf) & !is.na(dataTest2$return_rf)]
attach(dataTest)
dataTri = dataTest[order(AIM_t1),]
dataTri
detach(dataTest)
count = 1
count2 = 1
for (i in dataTri) {
  if (count2 <= nbAsset & dataTri$"stock_number"[count] %in% stockNumber) {
    dataSing = list()
    dataSing$"stock_number" = dataTri$"stock_number"[count]
    dataSing$"return_rf" = dataTri$"return_rf"[count]
    ptfPast <- c(ptfPast, dataSing)
    count2 = count2 + 1
  }
  count = count + 1
}
year = year + 1
  
while (year < 2005) {
  dataTest =  data[data$month == month & data$year == year,]
  dataTest2 =  data[data$month == month & data$year == year + 1,]
  stockNumber = dataTest$stock_number[!is.na(dataTest$return_rf) & !is.na(dataTest2$return_rf)]
  attach(dataTest)
  dataTri = dataTest[order(AIM_t1),]
  dataTri
  detach(dataTest)
  count = 1
  count2 = 1
  for (i in dataTri) {
    if (count2 <= nbAsset & dataTri$"stock_number"[count] %in% stockNumber) {
      dataSing = list()
      dataSing$"stock_number" = dataTri$"stock_number"[count]
      dataSing$"return_rf" = dataTri$"return_rf"[count]
      ptfCurr <- c(ptfCurr, dataSing)
      count2 = count2 + 1
    }
    count = count + 1
  }
  
  pnl = 0
  for (i in 1:length(ptfPast)) {
    if (i %% 2 == 1 & length(data[data$year == year & data$month == month & data$stock_number == ptfPast[i],]$return_rf) != 0) {
      pnl = pnl + data[data$year == year & data$month == month & data$stock_number == ptfPast[i],]$return_rf
      print(data[data$year == year & data$month == month & data$stock_number == ptfPast[i],]$return_rf)
    }
  }
  pnl = pnl/nbAsset
  ptfPast = ptfCurr
  ptfCurr = c()
  
  x <- c(x,year)
  y <- c(y,pnl)
  year = year + 1
}
plot(x,y, xlab = "Temps", ylab = "P&L", type = "l")
```

```{r}
# Plot
plot(x,y, xlab = "Temps", ylab = "P&L", type = "l")
mean = mean(y)
sd = sd(y)
lines(c(min(x),max(x)), c(mean, mean), type="o", pch=22, lty=2, col="blue")
lines(c(min(x),max(x)), c(mean + sd, mean + sd), type="o", pch=22, lty=2, col="red")
lines(c(min(x),max(x)), c(mean - sd, mean - sd), type="o", pch=22, lty=2, col="red")
```

