---
title: "Projet de microstructure"
author: "Mathilde Berregard, Théophile Charmont, Mohammed Fellaji, Alexandra Herbadji, Ayoub Jarraya"
date: "13/03/2018"
output: html_document
---

## 

``` {r echo=FALSE}
#installer et télécharger le package xlsx
install.packages("xlsx")
install.packages("rJava")
install.packages("xlsxjars")
install.packages("readxl")
```
## importation des données

``` {r echo=FALSE}
# Ouverture du fichier Excel et importation des données présentes sur la feuille 1
#Sys.setenv(JAVA_HOME='C:\\Program Files (x86)\\Java\\jre1.8.0_161')
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre1.8.0_161')
library(rJava)
library(xlsx)
library(readxl)
data_final_facteurs_fusionne_2 <- read_excel("../data_final_facteurs_fusionne_2.xlsx", 1)
```

## Statistiques descriptives
``` {r echo=FALSE}

vecteurRenta <- data_final_facteurs_fusionne_2["return_rf"]
summary(vecteurRenta)

vecteurBeta <- data_final_facteurs_fusionne_2["beta"]
summary(vecteurBeta)

vecteurAIM <- data_final_facteurs_fusionne_2["AIM"]
summary(vecteurAIM)

vecteurlogMarket <- data_final_facteurs_fusionne_2["log_market_cap"]
summary(vecteurlogMarket)

vecteurLogBTM <- data_final_facteurs_fusionne_2["log_btm"]
summary(vecteurLogBTM)
  
vecteurPIN <- data_final_facteurs_fusionne_2["pin"]
summary(vecteurPIN)
  
vecteurFsrv <- data_final_facteurs_fusionne_2["fsrv"]
summary(vecteurFsrv)
  
vecteurTurnover <- data_final_facteurs_fusionne_2["turnover"]
summary(vecteurTurnover)
  
vecteurIlliqAmu <- data_final_facteurs_fusionne_2["illiq_amihud"]
summary(vecteurIlliqAmu)
  
vecteurBetaSMB <- data_final_facteurs_fusionne_2["betaSMB"]
summary(vecteurBetaSMB)
  
vecteurBetaHML <- data_final_facteurs_fusionne_2["betaHML"]
summary(vecteurBetaHML)
  
vecteurBetaMOM <- data_final_facteurs_fusionne_2["betaMOM"]
summary(vecteurBetaMOM)
  
vecteurMarketReturn <- data_final_facteurs_fusionne_2["Marketretrun"]
summary(vecteurMarketReturn)
  
vecteurSMB <- data_final_facteurs_fusionne_2["SmallMinusBig"]
summary(vecteurSMB)
  
vecteurHML <- data_final_facteurs_fusionne_2["HighMinusLow"]
summary(vecteurBetaHML)
  
vecteurMOM <- data_final_facteurs_fusionne_2["MomentumFactor"]
summary(vecteurMOM)


```
## Etude de la corrélation de AIM

``` {r echo=FALSE}
'vecteurAIM <- data_final_facteurs_fusionne_2["AIM"]
vecteurBeta <- data_final_facteurs_fusionne_2[""]
cor()'

```

## Regression linéaire
``` {r echo=FALSE}

x = c()
y = c()
year = 1965
month = 1
date = 0

vectorRentaB <- c()

vectorRentaPin= c()

vectorRentaAIM = c()

vectorRentaAIMBb = c()
vectorRentaAIMBa = c()

vectorRentaABPa = c()
vectorRentaABPb = c()
vectorRentaABPp = c()

vectorAllb = c()
vectorAlla = c()
vectorAlllm = c()
vectorAlllb = c()
vectorAllp = c()
vectorAllfsrv = c()
vectorAllt = c()
vectorAllilli = c()
vectorAllSMB = c()
vectorAllHML = c()
vectorAllMOM = c()

vectorAllb1 = c()
vectorAlla1 = c()
vectorAlllm1 = c()
vectorAlllb1 = c()
vectorAllfsrv1 = c()
vectorAllt1 = c()
vectorAllilli1 = c()
vectorAllSMB1 = c()
vectorAllHML1 = c()
vectorAllMOM1 = c()

vector3paramsa = c()
vector3paramsb = c()
vector3paramsf = c()



while (year < 2005) {
  dataTest =  data_final_facteurs_fusionne_2[data_final_facteurs_fusionne_2$month == month & data_final_facteurs_fusionne_2$year == year,]
  
  if (length(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)])!=0) 
  {
  estimationRentaBeta <- lm(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)]~dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$beta_t1)])
  
  vectorRentaB <- rbind(vectorRentaB, coef(estimationRentaBeta)[2])
  
  }
  
  if (length(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$pin_t1)])!=0) 
  {
     estimationRentaPin <- lm(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$pin_t1)]~dataTest$pin_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$pin_t1)])
  
  vectorRentaPin <- rbind(vectorRentaPin, coef(estimationRentaPin)[2])



  }
  
  if (length(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1)])!=0) 
  {
     estimationRentaAIM <- lm(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1)]~dataTest$AIM_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1)])
  
  vectorRentaAIM  <- rbind(vectorRentaAIM, coef(estimationRentaAIM)[2])

  }
  
   if (length(dataTest$return_rf[!is.na(dataTest$return_rf) & (!is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1))] ) !=0) 
  {
     estimationRentaAIMB <- lm(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1)]~dataTest$AIM_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1)] + dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1)] )

  vectorRentaAIMBb  <- rbind(vectorRentaAIMBb, coef(estimationRentaAIMB)[2])
  vectorRentaAIMBa  <- rbind(vectorRentaAIMBa, coef(estimationRentaAIMB )[3])
  
  
   }
  
   if (length(dataTest$return_rf[!is.na(dataTest$return_rf) & (!is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$pin_t1) )] ) !=0) 
  {
     estimationRentaABP <- lm(dataTest$return_rf[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$pin_t1) ]~dataTest$AIM_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1)  & !is.na(dataTest$pin_t1)] + dataTest$beta_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$pin_t1)] + dataTest$pin_t1[!is.na(dataTest$return_rf) & !is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$pin_t1)] )

  vectorRentaABPb  <- rbind(vectorRentaABPb, coef(estimationRentaABP)[2])
  vectorRentaABPa  <- rbind(vectorRentaABPa, coef(estimationRentaABP )[3])
  vectorRentaABPp  <- rbind(vectorRentaABPp, coef(estimationRentaABP )[4])
  
   }
  
  condition = !is.na(dataTest$return_rf) & (!is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$pin_t1) & !is.na(dataTest$log_market_cap_t1) & !is.na(dataTest$log_btm_t1) & !is.na(dataTest$fsrv_t1) & !is.na(dataTest$turnover_t1)  & !is.na(dataTest$illiq_amihud_t1)  & !is.na(dataTest$betaSMB_t1) & !is.na(dataTest$betaHML_t1) & !is.na(dataTest$betaMOM_t1) )
  
   if (length(dataTest$return_rf[condition] ) !=0) 
  {
     estimationAll <- lm(dataTest$return_rf[condition]~dataTest$beta_t1[condition] + dataTest$AIM_t1[condition] + dataTest$log_market_cap_t1[condition] +  dataTest$log_btm_t1[condition] +  dataTest$pin_t1[condition] + dataTest$fsrv_t1[condition] +  dataTest$turnover_t1[condition] +  dataTest$illiq_amihud_t1[condition] + dataTest$betaSMB_t1[condition] +  dataTest$betaHML_t1[condition] + dataTest$betaMOM_t1[condition])

 
  
vectorAllb = rbind(vectorAllb, coef(estimationAll)[2])
vectorAlla = rbind(vectorAlla, coef(estimationAll)[3])
vectorAlllm = rbind(vectorAlllm, coef(estimationAll)[4])
vectorAlllb = rbind(vectorAlllb, coef(estimationAll)[5])
vectorAllp = rbind(vectorAllp, coef(estimationAll)[6])
vectorAllfsrv = rbind(vectorAllfsrv, coef(estimationAll)[7])
vectorAllt = rbind(vectorAllt, coef(estimationAll)[8])
vectorAllilli = rbind(vectorAllilli, coef(estimationAll)[9])
vectorAllSMB = rbind(vectorAllSMB, coef(estimationAll)[10])
vectorAllHML = rbind(vectorAllHML, coef(estimationAll)[11])
vectorAllMOM = rbind(vectorAllMOM, coef(estimationAll)[12])
  
   }
  
    condition1 = !is.na(dataTest$return_rf) & (!is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1)  & !is.na(dataTest$log_market_cap_t1) & !is.na(dataTest$log_btm_t1) & !is.na(dataTest$fsrv_t1) & !is.na(dataTest$turnover_t1)  & !is.na(dataTest$illiq_amihud_t1)  )
  
   if (length(dataTest$return_rf[condition1] ) !=0) 
  {
     estimationAll <- lm(dataTest$return_rf[condition1]~dataTest$beta_t1[condition1] + dataTest$AIM_t1[condition1] + dataTest$log_market_cap_t1[condition1] +  dataTest$log_btm_t1[condition1] + dataTest$fsrv_t1[condition1] +  dataTest$turnover_t1[condition1] +  dataTest$illiq_amihud_t1[condition1] )

 
  
vectorAllb1 = rbind(vectorAllb, coef(estimationAll)[2])
vectorAlla1 = rbind(vectorAlla, coef(estimationAll)[3])
vectorAlllm1 = rbind(vectorAlllm, coef(estimationAll)[4])
vectorAlllb1 = rbind(vectorAlllb, coef(estimationAll)[5])
vectorAllfsrv1 = rbind(vectorAllfsrv, coef(estimationAll)[6])
vectorAllt1 = rbind(vectorAllt, coef(estimationAll)[7])
vectorAllilli1 = rbind(vectorAllilli, coef(estimationAll)[8])
  
   }
    
condition3params = !is.na(dataTest$return_rf) & (!is.na(dataTest$AIM_t1) & !is.na(dataTest$beta_t1) & !is.na(dataTest$betaMOM_t1) )
    
if (length(dataTest$return_rf[condition3params] ) !=0) 
  {
     estimation3params <- lm(dataTest$return_rf[condition3params ]~dataTest$AIM_t1[condition3params] + dataTest$beta_t1[condition3params] + dataTest$betaMOM_t1[condition3params] )

  vector3paramsa  <- rbind(vector3paramsa , coef(estimation3params)[2])
  vector3paramsb   <- rbind(vector3paramsb , coef(estimation3params )[3])
  vector3paramsf   <- rbind(vector3paramsf , coef(estimation3params )[4])
  
   }
  


  
  month = month + 1
  date = date + 1
  if (month == 13) {
    month = 1
    year = year + 1
  }
}


print(mean(vectorRentaB))
t.test(vectorRentaB, conf.level = 0.95)

print(mean(vectorRentaAIM))

t.test(vectorRentaAIM, conf.level = 0.95)

t.test(vectorRentaPin,  conf.level = 0.95)

t.test(vectorRentaAIMBb,  conf.level = 0.95)
t.test(vectorRentaAIMBa,  conf.level = 0.95)

t.test(vectorRentaABPb,  conf.level = 0.95)
t.test(vectorRentaABPa,  conf.level = 0.95)
t.test(vectorRentaABPp,  conf.level = 0.95)

t.test(vectorAllb,  conf.level = 0.95)
t.test(vectorAlla,  conf.level = 0.95)
t.test(vectorAlllm,  conf.level = 0.95)
t.test(vectorAlllb,  conf.level = 0.95)
t.test(vectorAllp,  conf.level = 0.95)
t.test(vectorAllfsrv,  conf.level = 0.95)
t.test(vectorAllt,  conf.level = 0.95)
t.test(vectorAllilli,  conf.level = 0.95)
t.test(vectorAllSMB,  conf.level = 0.95)
t.test(vectorAllHML,  conf.level = 0.95)
t.test(vectorAllMOM,  conf.level = 0.95)

t.test(vectorAllb1,  conf.level = 0.95)
t.test(vectorAlla1,  conf.level = 0.95)
t.test(vectorAlllm1,  conf.level = 0.95)
t.test(vectorAlllb1,  conf.level = 0.95)
t.test(vectorAllfsrv1,  conf.level = 0.95)
t.test(vectorAllt1,  conf.level = 0.95)
t.test(vectorAllilli1,  conf.level = 0.95)

t.test(vector3paramsa,  conf.level = 0.95)
t.test(vector3paramsb,  conf.level = 0.95)
t.test(vector3paramsf,  conf.level = 0.95)







```

``` {r echo=FALSE}
moyenneRentaBeta = moyenneRentaBeta/date
summary(moyenneRentaBeta)

vecteurRenta <- data_final_facteurs_fusionne_2["return_rf"]

vecteurBeta <- data_final_facteurs_fusionne_2["beta"]

estimationRentaBeta <- lm(data_final_facteurs_fusionne_2$return_rf~data_final_facteurs_fusionne_2$beta)

estimationRentaAIM <- lm(data_final_facteurs_fusionne_2$return_rf~data_final_facteurs_fusionne_2$AIM_t1)

estimationRentaBetaAim <- lm(data_final_facteurs_fusionne_2$return_rf~data_final_facteurs_fusionne_2$beta_t1 + data_final_facteurs_fusionne_2$AIM_t1)

estimationRentaPin <- lm(data_final_facteurs_fusionne_2$return_rf~data_final_facteurs_fusionne_2$pin_t1)

estimationGlobale <- lm(data_final_facteurs_fusionne_2$return_rf~data_final_facteurs_fusionne_2$beta_t1 + data_final_facteurs_fusionne_2$AIM_t1 + data_final_facteurs_fusionne_2$log_market_cap_t1 + data_final_facteurs_fusionne_2$log_btm_t1 + data_final_facteurs_fusionne_2$pin_t1 + data_final_facteurs_fusionne_2$fsrv_t1 + data_final_facteurs_fusionne_2$turnover_t1 + data_final_facteurs_fusionne_2$illiq_amihud_t1 + data_final_facteurs_fusionne_2$betaSMB_t1 + data_final_facteurs_fusionne_2$betaHML_t1 + data_final_facteurs_fusionne_2$betaMOM_t1)



summary(estimationGlobale)

print(coef(estimationGlobale)[3])

summary(estimationGlobale)[[4]][2,4]

```


